import type { Task } from "@/types";

const tasks: Task[] = [
  {
    id: "t1",
    code: "T-101",
    projectId: "p1",
    name: "Investigación de usuarios",
    assignedId: "m1",
    priority: "high",
    status: "completed",
    progress: 100,
    startDate: "2026-06-15",
    endDate: "2026-06-17",
  },
  {
    id: "t2",
    code: "T-102",
    projectId: "p1",
    name: "Definición de arquitectura",
    assignedId: "m2",
    priority: "high",
    status: "completed",
    progress: 100,
    startDate: "2026-06-15",
    endDate: "2026-06-18",
  },
  {
    id: "t3",
    code: "T-103",
    projectId: "p1",
    name: "Diseño del sistema visual",
    assignedId: "m3",
    priority: "medium",
    status: "in-progress",
    progress: 65,
    startDate: "2026-06-17",
    endDate: "2026-06-24",
  },
  {
    id: "t4",
    code: "T-104",
    projectId: "p1",
    name: "Setup del repositorio y CI/CD",
    assignedId: "m2",
    priority: "medium",
    status: "completed",
    progress: 100,
    startDate: "2026-06-18",
    endDate: "2026-06-20",
  },
  {
    id: "t5",
    code: "T-105",
    projectId: "p1",
    name: "Wireframes de baja fidelidad",
    assignedId: "m1",
    priority: "medium",
    status: "completed",
    progress: 100,
    startDate: "2026-06-18",
    endDate: "2026-06-22",
  },
  {
    id: "t6",
    code: "T-106",
    projectId: "p1",
    name: "Modelo de datos y schema",
    assignedId: "m2",
    priority: "high",
    status: "in-progress",
    progress: 50,
    startDate: "2026-06-20",
    endDate: "2026-06-26",
  },
  {
    id: "t7",
    code: "T-107",
    projectId: "p1",
    name: "Componentes UI base",
    assignedId: "m3",
    priority: "high",
    status: "in-progress",
    progress: 40,
    startDate: "2026-06-22",
    endDate: "2026-06-29",
  },
  {
    id: "t8",
    code: "T-108",
    projectId: "p1",
    name: "Prototipo navegable",
    assignedId: "m1",
    priority: "medium",
    status: "in-progress",
    progress: 30,
    startDate: "2026-06-23",
    endDate: "2026-06-30",
  },
  {
    id: "t9",
    code: "T-109",
    projectId: "p1",
    name: "API de autenticación",
    assignedId: "m2",
    priority: "high",
    status: "blocked",
    progress: 15,
    startDate: "2026-06-26",
    endDate: "2026-07-03",
  },
  {
    id: "t10",
    code: "T-110",
    projectId: "p1",
    name: "Componente de Gantt (timeline)",
    assignedId: "m3",
    priority: "high",
    status: "pending",
    progress: 0,
    startDate: "2026-06-29",
    endDate: "2026-07-10",
  },
  {
    id: "t11",
    code: "T-111",
    projectId: "p1",
    name: "Pruebas de usabilidad",
    assignedId: "m1",
    priority: "low",
    status: "pending",
    progress: 0,
    startDate: "2026-07-01",
    endDate: "2026-07-06",
  },
  {
    id: "t12",
    code: "T-112",
    projectId: "p1",
    name: "Integración API de tareas",
    assignedId: "m2",
    priority: "medium",
    status: "pending",
    progress: 0,
    startDate: "2026-07-03",
    endDate: "2026-07-12",
  },
  {
    id: "t13",
    code: "T-113",
    projectId: "p1",
    name: "QA y despliegue a staging",
    assignedId: "m3",
    priority: "high",
    status: "pending",
    progress: 0,
    startDate: "2026-07-10",
    endDate: "2026-07-18",
  },
];

export function getTasks(): Task[] {
  return tasks;
}

export function getTaskByProject(projectId: string): Task[] {
  return tasks.filter((task) => task.projectId === projectId);
}

export function getTaskNyId(id: string): Task | undefined {
  return tasks.find((task) => task.id === id);
}
